codecov:
  require_ci_to_pass: false
  bot: null

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 80% #overall project/ repo coverage
    patch:
      default:
        target: 65%  

ignore:
  - "**/*Buyback*.sol"
